on:
  pull_request: null
  push:
    branches:
      - '*.*'

name: phpunit

jobs:
  phpunit:
    uses: spiral/gh-actions/.github/workflows/phpunit.yml@master
    with:
      test-server: true
      os: >-
        ['ubuntu-latest']
      stability: >-
        ['prefer-lowest', 'prefer-stable']
